---

- name: Clone "stijink/temperature-sensor-ds18b20" from GitHub
  git:
    repo: 'https://github.com/stijink/temperature-sensor-ds18b20.git'
    dest: /opt/temperature-sensor-ds18b20

- name: Install node dependencies
  command: npm install
  args:
    chdir: /opt/temperature-sensor-ds18b20
    creates: /opt/temperature-sensor-ds18b20/node_modules

- name: Add to pm2 start list
  command: pm2 start /opt/temperature-sensor-ds18b20/server.js --name="temperature-sensor-ds18b20" --watch
  become: false
  ignore_errors: yes
