---

- name: Clone "stijink/temperature-sensor-ds18b20" from GitHub
  git:
    repo: 'https://github.com/stijink/temperature-sensor-ds18b20.git'
    dest: /opt/temperature-sensor-ds18b20

- name: Install node dependencies
  command: npm install
  args:
    chdir: /opt/temperature-sensor-ds18b20
    creates: /opt/temperature-sensor-ds18b20/node_modules

- name: Create "systemd" service file for temperature-sensor-ds18b20
  template:
    src: temperature-sensor-ds18b20.service
    dest: /etc/systemd/system/temperature-sensor-ds18b20.service
    owner: root

- name: Start service "temperature-sensor-ds18b20" and enable at bootup
  service:
    name: temperature-sensor-ds18b20
    state: started
    enabled: yes
