engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "api/phpmd.xml"
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- app/node_modules/
- api/tests/
- api/vendor/
