---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- node_modules/
- tests/
- vendor/
