language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  allow_failures:
  - php: '7.2'  

install: composer install
script: vendor/bin/phpunit

after_success:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
