language: php
php:
  - '7.1'
  - '7.2'

install: cd api && composer install
script: vendor/bin/phpunit

after_success:
  - vendor/bin/test-reporter

after_failure:
  - cat var/log/test.log

addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
