version: '3.4'
services:
    homescreen:
        build:
            context: .
            target: development
        image: stijink/homescreen:dev
        working_dir: /var/www
        environment:
            - APP_ENV=dev
        ports:
            - "5001:80"
