version: '3.4'
services:
    homescreen:
        image: registry.tijink.de/homescreen:latest
        environment:
            - APP_ENV=prod
        ports:
            - "5001:80"
        deploy:
            replicas: 1
            placement:
                constraints: [node.hostname == homescreen]