version: '2'
services:

  api:
    build:
      context: ./build
      dockerfile: Dockerfile-api
    image: stijink/homescreen-api
    working_dir: ${WORKDIR}
    ports:
      - "${PORT}:80"
    volumes:
      - ./api/:${WORKDIR}:delegated
      - app-assets:${WORKDIR}/public/assets:delegated
    environment:
      - APP_ENV
    tmpfs:
      - ${WORKDIR}/var

  app:
    image: node:lts-alpine
    working_dir: ${WORKDIR}
    command: node_modules/webpack/bin/webpack.js --watch
    volumes:
      - ./app/:${WORKDIR}:delegated
      - app-assets:${WORKDIR}/assets:delegated

volumes:
  app-assets:
