version: '3'
services:

  homescreen-api:
    build:
      context: ./build
      dockerfile: Dockerfile-api
    restart: ${RESTART_POLICY}
    image: stijink/homescreen-api
    container_name: homescreen-api
    working_dir: ${WORKDIR}
    ports:
      - "${PORT}:80"
    volumes:
      - ./api/:${WORKDIR}
      - app-assets:${WORKDIR}/public/assets
    environment:
      - APP_ENV

  homescreen-app:
    build:
      context: ./build
      dockerfile: Dockerfile-app
    image: stijink/homescreen-app
    working_dir: ${WORKDIR}
    container_name: homescreen-app
    command: node_modules/webpack/bin/webpack.js --watch
    volumes:
      - ./app/:${WORKDIR}
      - app-assets:${WORKDIR}/assets

volumes:
  app-assets:
