version: '3.4'
services:
    homescreen:
        image: stijink/homescreen:latest
        environment:
            - APP_ENV=prod
        ports:
            - "5001:80"
        deploy:
            replicas: 1