---

- name: Clone "stijink/hue-raspberry-hdmi" from GitHub
  git:
    repo: 'https://github.com/stijink/hue-raspberry-hdmi.git'
    dest: /opt/hue-raspberry-hdmi

- name: Install node dependencies
  command: npm install
  args:
    chdir: /opt/hue-raspberry-hdmi
    creates: /opt/hue-raspberry-hdmi/node_modules

- name: Create "systemd" service file for hue-raspberry-hdmi
  template:
    src: hue-raspberry-hdmi.service
    dest: /etc/systemd/system/hue-raspberry-hdmi.service
    owner: root

- name: Start service "hue-raspberry-hdmi" and enable at bootup
  service:
    name: hue-raspberry-hdmi
    state: started
    enabled: yes
