---

- name: Clone "stijink/raspberry-status-server" from GitHub
  git:
    repo: 'https://github.com/stijink/raspberry-status-server.git'
    dest: /opt/raspberry-status-server

- name: Install node dependencies
  command: npm install
  args:
    chdir: /opt/raspberry-status-server
    creates: node_modules

- name: Add to pm2 start list
  command: pm2 start /opt/raspberry-status-server/index.js --name="raspberry-status-server" --watch
  become: false
  ignore_errors: yes
