parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Component\:
        resource: '../src/Component/*'

    App\Command\:
        resource: '../src/Command/*'

    App\Configuration:
      arguments: ['%kernel.project_dir%/config/config.json']

    # Third party services we want to use with autowiring
    Laminas\Feed\Reader\Reader: ~
