---
- hosts: all

  roles:
    - { role: base-configuration, become: true }
    - { role: nodejs, become: true }
    - { role: homescreen, become: false }
    - { role: clanedars-cronjob, become: true }
    - { role: pm2-install, become: true }
    - { role: hue-raspberry-hdmi, become: false }
    - { role: raspberry-status-server, become: false }
    - { role: temperature-sensor-ds18b20, become: false }
    - { role: pm2-rebootable, become: true }
