name: Homescreen Api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    strategy:
      matrix:
        php: ['7.3', '7.4']    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}      

    - name: Validate composer.json and composer.lock
      run: composer validate --working-dir=api/

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: api/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest --working-dir=api/

    - name: Lint symfony container
      run: api/bin/console lint:container

    - name: Lint YAML Files
      run: api/bin/console lint:yaml api/config
